name: TapDrink
description: App to you have fun with your friends.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  google_fonts:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^0.1.9
  flutter_launcher_icons: ^0.7.2
  provider: any

flutter_native_splash:
  image: assets/icon/splashScren.png
  color: "ff9800"

flutter_icons:
  image_path: "assets/icon/TapDrink.png"
  android: true
  ios: true

flutter:

  uses-material-design: true

  assets:
   - assets/icon/
   - assets/images/15game.jpg
   - assets/images/tapdrink.jpg

  # fonts:
  # - family: Big Shoulders Display
  #   fonts:
  #     - asset: assets/fonts/BigShouldersDisplay-Light.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #

